server:
  port: 10020

spring:
  application:
    name: phone-book-service
  datasource:
    url: jdbc:postgresql://localhost:5432/<database>
    username: <username>
    password: <password>
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
